package ant.sql.astnode;
/* Generated By:JavaCC: Do not edit this line. AntWhereParserTreeConstants.java Version 6.0_1 */
public interface AntWhereParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTORNODE = 1;
  public int JJTANDNODE = 2;
  public int JJTBLOKNODE = 3;
  public int JJTLTNODE = 4;
  public int JJTGTNODE = 5;
  public int JJTLENODE = 6;
  public int JJTGENODE = 7;
  public int JJTEQNODE = 8;
  public int JJTNEQNODE = 9;
  public int JJTFILEDEXPRESSION = 10;
  public int JJTVALUEEXPRESSION = 11;


  public String[] jjtNodeName = {
    "void",
    "OrNode",
    "AndNode",
    "BlokNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "EQNode",
    "NEQNode",
    "FiledExpression",
    "valueExpression",
  };
}
/* JavaCC - OriginalChecksum=7faa3a921048993be765409eb7d3d48c (do not edit this line) */
