package ant.sql.astnode;
/* Generated By:JJTree: Do not edit this line. ASTAndNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAndNode extends SimpleNode {
  public ASTAndNode(int id) {
    super(id);
  }

  public ASTAndNode(AntWhereParser p, int id) {
    super(p, id);
  }
  public void interpret()
  {
	 ((SimpleNode)children[0]).interpret();
     if (!((Boolean)stack[top]).booleanValue())
     {
        stack[top] = new Boolean(false);
        return;
     }
     ((SimpleNode)children[1]).interpret();
     boolean left=((Boolean)stack[top]).booleanValue();
     boolean right=((Boolean)stack[top - 1]).booleanValue();
     stack[--top] = new Boolean(left&&right);
                               
  }
}
/* JavaCC - OriginalChecksum=0d5cba2c6a544ce31c986e0851ec898a (do not edit this line) */
