package ant.sql.astnode;
/* Generated By:JJTree: Do not edit this line. ASTFiledExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFiledExpression extends SimpleNode {
  public ASTFiledExpression(int id) {
    super(id);
  }

  public ASTFiledExpression(AntWhereParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50f7f741cb060668e8ff0e89efb04057 (do not edit this line) */
