package ant.sql.astnode;
/* Generated By:JJTree: Do not edit this line. ASTOrNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOrNode extends SimpleNode {
  public ASTOrNode(int id) {
    super(id);
  }

  public ASTOrNode(AntWhereParser p, int id) {
    super(p, id);
  }
  public void interpret()
  {
	 ((SimpleNode)children[0]).interpret();
     if (((Boolean)stack[top]).booleanValue())
     {
        stack[top] = new Boolean(true);
        return;
     }
     ((SimpleNode)children[1]).interpret();
     boolean left=((Boolean)stack[top]).booleanValue();
     boolean right=((Boolean)stack[top - 1]).booleanValue();
     
     stack[--top] = new Boolean(left ||
    		 right);
  }
}
/* JavaCC - OriginalChecksum=a70899ea87070f725a47717f6c01f336 (do not edit this line) */
