package ant.sql.astnode;
/* Generated By:JJTree: Do not edit this line. ASTvalueExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvalueExpression extends SimpleNode {
  public ASTvalueExpression(int id) {
    super(id);
  }

  public ASTvalueExpression(AntWhereParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa3867cf1526dcbb1b11735bdc369f1f (do not edit this line) */
